# Generated by Django 2.1.5 on 2019-01-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_auto_20190117_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='datasets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Dataset'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Experiment'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organismModifications',
            field=models.TextField(default='None', help_text='Organism Modifications'),
        ),
    ]
