# Generated by Django 2.1.5 on 2019-01-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_auto_20190117_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='datasets',
        ),
        migrations.AddField(
            model_name='dataset',
            name='sample',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Sample'),
        ),
    ]
