# Generated by Django 2.1.5 on 2019-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_auto_20190117_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['sampleName']},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampleID',
            field=models.IntegerField(help_text='Integer Field', primary_key=True, serialize=False),
        ),
    ]
