# Generated by Django 2.1.5 on 2019-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0005_auto_20190118_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='sample',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampleName',
            field=models.TextField(help_text='Sample Name', verbose_name='Sample Name'),
        ),
    ]
