# Generated by Django 2.1.5 on 2019-01-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0008_auto_20190118_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampleID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
