# Generated by Django 2.1.5 on 2019-01-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0009_auto_20190118_1529'),
        ('Records', '0010_auto_20190118_1601'),
    ]

    operations = [
    ]
