# Generated by Django 2.1.5 on 2019-01-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0012_auto_20190122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='datasetID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Dataset ID'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experimentID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Experiment ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampleID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
