# Generated by Django 2.1.5 on 2019-01-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0017_auto_20190123_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='dateCreated',
            new_name='_dateCreated',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='fileLocation',
            new_name='_fileLocation',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='operator',
            new_name='_operator',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='status',
            new_name='_status',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='type',
            new_name='_type',
        ),
    ]
