# Generated by Django 2.1.5 on 2019-01-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0019_auto_20190123_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='IRB',
            new_name='_IRB',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experimentName',
            new_name='_experimentName',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experimentalDesign',
            new_name='_experimentalDesign',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='projectLead',
            new_name='_projectLead',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='teamMembers',
            new_name='_teamMembers',
        ),
    ]
