# Generated by Django 2.1.5 on 2019-01-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0021_remove_sample_experiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='experimentID',
            new_name='_experimentID',
        ),
    ]
