# Generated by Django 2.1.5 on 2019-01-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0023_auto_20190123_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='dateCreated',
            new_name='_dateCreated',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='organism',
            new_name='_organism',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='organismModifications',
            new_name='_organismModifications',
        ),
    ]
