# Generated by Django 2.1.5 on 2019-01-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0024_auto_20190123_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='sampleID',
            new_name='_sampleID',
        ),
    ]
