# Generated by Django 2.1.5 on 2019-01-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0027_dataset__sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='_sample',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Sample', verbose_name='Sample'),
        ),
    ]
