# Generated by Django 2.1.5 on 2019-01-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0028_auto_20190124_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='_sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Records.Sample', verbose_name='Sample'),
        ),
    ]
