# Generated by Django 2.1.5 on 2019-01-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0029_auto_20190124_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='_instrumentSetting',
            new_name='instrumentSetting',
        ),
    ]
