# Generated by Django 2.1.5 on 2019-01-30 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0034_auto_20190130_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='_dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='_dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='_experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.Experiment', verbose_name='Experiment'),
        ),
    ]
