# Generated by Django 2.1.5 on 2019-01-31 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0035_auto_20190130_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments, Notes, or Details'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_fileHash',
            field=models.TextField(blank=True, null=True, verbose_name='File Hash'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_fileName',
            field=models.TextField(blank=True, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_fileSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_instrumentSetting',
            field=models.TextField(blank=True, null=True, verbose_name='link to instrument settings'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_operator',
            field=models.TextField(help_text='The team member who ran the machine.', verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='_IRB',
            field=models.IntegerField(blank=True, null=True, verbose_name='IRB Number'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='_teamMembers',
            field=models.TextField(blank=True, null=True, verbose_name='Team Members'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Experiment', verbose_name='Experiment'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='_organismModifications',
            field=models.TextField(blank=True, default='None', null=True, verbose_name='Organism Modifications'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='_treatmentProtocol',
            field=models.TextField(blank=True, null=True, verbose_name='Treatment Protocol'),
        ),
    ]
