# Generated by Django 2.1.5 on 2019-02-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0036_auto_20190131_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='_experimentalDesign',
            new_name='experimentalDesign',
        ),
    ]
