# Generated by Django 2.1.5 on 2019-02-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0037_auto_20190131_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='experimentalDesign',
            new_name='_experimentalDesign',
        ),
    ]
