# Generated by Django 2.1.5 on 2019-02-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0038_auto_20190131_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailedField',
            fields=[
                ('_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('_description', models.TextField(blank=True, null=True)),
                ('_file', models.FileField(upload_to='', verbose_name='Descriptive files or images')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentSetting',
            fields=[
                ('detailedfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Records.detailedField')),
            ],
            bases=('Records.detailedfield',),
        ),
    ]
