# Generated by Django 2.1.5 on 2019-02-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0039_detailedfield_instrumentsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDesign',
            fields=[
                ('detailedfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Records.detailedField')),
            ],
            bases=('Records.detailedfield',),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('detailedfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Records.detailedField')),
            ],
            bases=('Records.detailedfield',),
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(upload_to='', verbose_name='Related file or images'),
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='instrumentsetting',
            name='_instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Instrument', verbose_name='Experiment'),
        ),
    ]
