# Generated by Django 2.1.5 on 2019-02-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0040_auto_20190201_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentsetting',
            name='_instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.Instrument', verbose_name='Instrument'),
        ),
    ]
