# Generated by Django 2.1.5 on 2019-02-01 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0041_auto_20190201_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='_instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.Instrument'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_instrumentSetting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.InstrumentSetting'),
        ),
    ]
