# Generated by Django 2.1.5 on 2019-02-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0042_auto_20190201_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments, Notes, or Details'),
        ),
        migrations.AddField(
            model_name='sample',
            name='_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments, Notes, or Details'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.Instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_instrumentSetting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.InstrumentSetting', verbose_name='Instrument Setting'),
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Related file or images'),
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
