# Generated by Django 2.1.5 on 2019-02-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0043_auto_20190204_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileStatusOptions',
            fields=[
                ('_option', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('detailedfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Records.detailedField')),
            ],
            bases=('Records.detailedfield',),
        ),
        migrations.RenameModel(
            old_name='ExperimentDesign',
            new_name='ExperimentalDesign',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.fileStatusOptions', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='_treatmentProtocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.Protocol', verbose_name='Treatment Protocol'),
        ),
    ]
