# Generated by Django 2.1.5 on 2019-02-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0044_auto_20190204_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileStatusOption',
            fields=[
                ('_option', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.fileStatusOption', verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='fileStatusOptions',
        ),
    ]
