# Generated by Django 2.1.5 on 2019-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0045_auto_20190204_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='_status',
            field=models.TextField(null=True, verbose_name='File Status'),
        ),
    ]
