# Generated by Django 2.1.5 on 2019-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0046_auto_20190204_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='_sample',
        ),
        migrations.AddField(
            model_name='dataset',
            name='_sample',
            field=models.ManyToManyField(to='Records.Sample', verbose_name='Sample'),
        ),
    ]
