# Generated by Django 2.1.5 on 2019-02-05 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0047_auto_20190204_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='_instrumentSetting',
            field=models.ForeignKey(blank=True, limit_choices_to={'instrument': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.Instrument', verbose_name='Instrument')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.InstrumentSetting', verbose_name='Instrument Setting'),
        ),
    ]
