# Generated by Django 2.1.5 on 2019-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0050_auto_20190205_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
