# Generated by Django 2.1.5 on 2019-02-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0051_fileread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileread',
            name='_file',
        ),
        migrations.AddField(
            model_name='fileread',
            name='_File',
            field=models.FileField(default='C/Users/M McCown/Downloads/alphaSheet.xlsx', upload_to=''),
            preserve_default=False,
        ),
    ]
