# Generated by Django 2.1.5 on 2019-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0055_auto_20190208_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Related file or images'),
        ),
    ]
