# Generated by Django 2.1.5 on 2019-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0057_auto_20190211_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileread',
            name='lead',
            field=models.CharField(default='Mr. Rogers', max_length=200),
            preserve_default=False,
        ),
    ]
