# Generated by Django 2.1.5 on 2019-02-25 20:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0061_auto_20190222_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentaldesign',
            name='_extra_fields',
            field=django_mysql.models.ListTextField(models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
