# Generated by Django 2.1.5 on 2019-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0063_auto_20190301_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/%m/%d/', verbose_name='Related file or images'),
        ),
        migrations.AlterField(
            model_name='detailedfield',
            name='_name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
    ]
