# Generated by Django 2.1.5 on 2019-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0065_backupfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfile',
            name='lead',
            field=models.CharField(default='NULL', max_length=200, verbose_name='Project Lead'),
            preserve_default=False,
        ),
    ]
