# Generated by Django 2.1.5 on 2019-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0066_backupfile_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfile',
            name='file',
            field=models.CharField(default='dump-2019-03-18.json', max_length=100, verbose_name='File Name'),
            preserve_default=False,
        ),
    ]
