# Generated by Django 2.1.5 on 2019-03-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0067_backupfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupfile',
            name='lead',
        ),
    ]
