# Generated by Django 2.1.5 on 2019-03-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0068_remove_backupfile_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentsetting',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
