# Generated by Django 2.1.5 on 2019-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0071_auto_20190513_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='_fileLocationRemote',
            field=models.TextField(blank=True, null=True, verbose_name='Path to remote (supercomputer) file location'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='_fileLocation',
            field=models.TextField(blank=True, null=True, verbose_name='Path to original file location'),
        ),
    ]
