# Generated by Django 2.1.5 on 2019-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0072_auto_20190523_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.FileField(upload_to='files/', verbose_name='File')),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='_treatmentProtocol',
            field=models.ManyToManyField(blank=True, to='Records.Protocol', verbose_name='Treatment Protocol'),
        ),
    ]
