# Generated by Django 2.1.5 on 2019-06-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0076_auto_20190620_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='_experimentalDesign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.ExperimentalDesign', verbose_name='Experimental Design'),
        ),
    ]
