# Generated by Django 2.1.5 on 2019-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0077_auto_20190621_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfield',
            name='_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
