# Generated by Django 2.1.5 on 2019-06-24 23:47

import Records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0079_remove_detailedfield__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedfield',
            name='_file',
        ),
        migrations.AlterField(
            model_name='file',
            name='_file',
            field=models.FileField(storage=Records.models.CheckDuplicateStorage(), upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
