# Generated by Django 2.1.5 on 2019-06-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0080_auto_20190624_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/%m/%d/', verbose_name='Related file or images'),
        ),
    ]
