# Generated by Django 2.1.5 on 2019-06-24 23:53

import Records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0081_detailedfield__file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedfield',
            name='_file',
            field=models.FileField(blank=True, null=True, storage=Records.models.CheckDuplicateStorage(), upload_to='C:\\Users\\M McCown\\SCS\\DataMan\\media/files/%Y/%m/%d/', verbose_name='Related file or images'),
        ),
    ]
